# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lcop < Formula
  desc "CLI tool that drives GitHub Copilot CLI through a structured implementation workflow"
  homepage "https://github.com/smartcrabai/longcop"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.2/longcop_darwin_amd64.tar.gz"
      sha256 "258687b52d4115e12adf06b08f7150151b77a68a4ce9bdc3043f20913d5b26c3"

      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.2/longcop_darwin_arm64.tar.gz"
      sha256 "ff68234910bf7cf4b7ddeafe7630097e32433f2921a225104da11c33ca567206"

      define_method(:install) do
        bin.install "lcop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.2/longcop_linux_amd64.tar.gz"
      sha256 "01c58ee2bde8400e1dbec427fe9891835470143033391511dc706932421c5ac8"
      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.2/longcop_linux_arm64.tar.gz"
      sha256 "7d5e3d12aa0d7048ebca20fd9414a701a9b9d37797603cc063440e40a1bbe3d7"
      define_method(:install) do
        bin.install "lcop"
      end
    end
  end
end
