# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lcop < Formula
  desc "CLI tool that drives GitHub Copilot CLI through a structured implementation workflow"
  homepage "https://github.com/smartcrabai/longcop"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.1/longcop_darwin_amd64.tar.gz"
      sha256 "b34c23afddecb3c75f269d5c3b816e54497f036c48ec4100e2172750abde5d44"

      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.1/longcop_darwin_arm64.tar.gz"
      sha256 "38b4f4f827730534d7c5b6bdb6928a9286a30e26dea28e7b0c18af387af62e0b"

      define_method(:install) do
        bin.install "lcop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.1/longcop_linux_amd64.tar.gz"
      sha256 "78875a1f77aace26ee84b7ec4954a1f134c58123d74d0bd34884747735330034"
      define_method(:install) do
        bin.install "lcop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smartcrabai/longcop/releases/download/v0.1.1/longcop_linux_arm64.tar.gz"
      sha256 "2f539f047cddabfa926b549059c2a57fbab9eae0bf2534a0ace5a85cfeda8378"
      define_method(:install) do
        bin.install "lcop"
      end
    end
  end
end
